RoleName: ComputeNestDeploy
ZoneId: ap-southeast-1a
VpcId: vpc-t4nqpdxw25u2i6eidt6yo
ServiceType: managed
VSwitchId: vsw-t4nr1hmvcmvknt43ebmhw
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: workhardliuzheng/mongodb
DockerComposeEnvPath: .env.example
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedValues:
  - root
  - master
  - main
  AllowedPattern: ''
  Label: 用户名
  ConstraintDescription: ''
  Default: root
  Name: MONGO_INITDB_ROOT_USERNAME
DockerComposeYamlPath: docker-compose.yaml
Owner: workhardliuzheng
Branch: main
Platform: github
