ServiceType: private
AllowedRegions:
- ap-southeast-1
ArtifactSourceType: DockerCompose
RepoName: aliyun-computenest/mongodb
DockerComposeEnvPath: .env.example
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: UserName
  ConstraintDescription: ''
  Default: admin
  Name: MONGO_INITDB_ROOT_USERNAME
- NoEcho: true
  Type: String
  AssociationProperty: ALIYUN::ECS::Instance::Password
  AllowedPattern: ''
  Label: Password
  ConstraintDescription: ''
  Name: MONGO_INITDB_ROOT_PASSWORD
DockerComposeYamlPath: docker-compose.yaml
Owner: Alicloud-ComputeNest
Branch: main
Platform: github
