RoleName: ComputeNestDeploy
ZoneId: cn-hangzhou-j
VpcId: vpc-bp11usn5o5pux4wk0xl04
ServiceType: managed
VSwitchId: vsw-bp18z1vgcerbttqvfcfbb
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: workhardliuzheng/mongodb
DockerComposeEnvPath: .env.example
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedValues:
  - root
  - master
  - admin
  AllowedPattern: ''
  Label: 用户名
  ConstraintDescription: ''
  Default: root
  Name: MONGO_INITDB_ROOT_USERNAME
DockerComposeYamlPath: docker-compose.yaml
Owner: workhardliuzheng
Branch: main
Platform: github
