Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: 'Template'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
    ModifyParametersConfig:
      - TemplateName: 'Template'
        Operation:
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
    
    ParameterConfigs:
      - TemplateName: 'Template'
        Parameters:
          
          Default.MONGO_INITDB_ROOT_USERNAME:
            Type: String
            Default: root 
            Description: 用户名
            
            
            
            
            
            AllowedValues:
              
              - root
              - test
              - admin
          
        Metadata:
           ParameterGroups:
             - Parameters:
                 - MONGO_INITDB_ROOT_USERNAME
               
               DefaultValue: |-
                  MONGO_INITDB_ROOT_USERNAME=root
                  MONGO_INITDB_ROOT_PASSWORD=pleaseChangeMe
                  
               Formatter: env
               Name: Default
    
  DeployMetadata:
    SupplierDeployMetadata:
      RoleName: ComputeNestDeploy
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: 'Template'
          Url: 'ros_templates/template.yaml'
          AllowedRegions:
            - ap-southeast-1
          PredefinedParameters: []
          HiddenParameterKeys:
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: vpc-t4nqpdxw25u2i6eidt6yo
                    ZoneId: ap-southeast-1a
                    VSwitchId: vsw-t4nr1hmvcmvknt43ebmhw
      ArtifactRelation:
        ecs_image_mongodb:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: demo
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_mongodb
    Description: mongodb EcsImage
    SupportRegionIds:
        - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: workhardliuzheng
        RepoName: workhardliuzheng/mongodb
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      CommandContent: |-
        mkdir -p /root/application
        if [ -e "/root/code/.env.example" ]; then cp -r "/root/code/.env.example" "/root/application/"; fi
        if [ -e "/root/code/mongodata" ]; then cp -r "/root/code/mongodata" "/root/application/"; fi
        if [ -e "/root/code/docker-compose.yaml" ]; then cp -r "/root/code/docker-compose.yaml" "/root/application/"; fi
        cd /root/application
        cp .env.example ./.env
        sed -i 's/pull_policy: always/pull_policy: if_not_present/g' docker-compose.yaml
        docker compose -f docker-compose.yaml build
        docker compose -f docker-compose.yaml pull || true;